//#region Info

/**
 * @file <h3>DropSuit</h3>
 * <p>
 *   DropSuit is a JavaScript(ES6) and Node.js(v14.x) module library
 *   created by Lado Oniani that offers a diverse collection of functions
 *   for natural language processing (NLP) and data manipulation.
 *   It provides a curated collection of original and classic techniques and methods
 *   for tasks such as text analysis, language understanding and generation,
 *   as well as for data manipulation tasks. Additionally,
 *   it includes unique tools and features for chatbot dialog flow logic
 *   and other specific use cases.
 *   The library is open-source and available under the Apache License 2.0.
 *   Whether you're a researcher, developer, or data scientist,
 *   DropSuit offers a range of tools to enhance your work,
 *   with a focus on diversity and experimentation.
 * </p>
 * @author Lado Oniani
 * {@link https://github.com/ladooniani GitHub}
 * @see mailto:ladooniani@gmail.com
 * @version 1.0.0
 * @see https://github.com/ladooniani/DropSuit#readme
 * @copyright 2016-2023 Lado Oniani - DropSuit. All Rights Reserved.
 * @license Apache License 2.0
 */

//#endregion

//#region 154 Stop words A

function stopwords_a() {
  let stopwords_a = [
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "also",
    "am",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "could",
    "did",
    "do",
    "does",
    "doing",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "having",
    "he",
    "he'd",
    "he'll",
    "he's",
    "her",
    "here",
    "here's",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "how's",
    "i",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "if",
    "in",
    "into",
    "is",
    "it",
    "it's",
    "its",
    "itself",
    "let's",
    "me",
    "more",
    "most",
    "my",
    "myself",
    "nor",
    "of",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "that's",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "there's",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "we",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "were",
    "what",
    "what's",
    "when",
    "when's",
    "where",
    "where's",
    "which",
    "while",
    "who",
    "who's",
    "whom",
    "why",
    "why's",
    "with",
    "would",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
  ];

  return stopwords_a;
}

//#endregion

//#region 32 Stop words B

function stopwords_b() {
  let stopwords_b = [
    "actually",
    "almost",
    "although",
    "always",
    "became",
    "become",
    "can",
    "either",
    "else",
    "hence",
    "just",
    "may",
    "maybe",
    "might",
    "mine",
    "must",
    "neither",
    "not",
    "oh",
    "ok",
    "whenever",
    "whereas",
    "wherever",
    "whether",
    "whoever",
    "whose",
    "will",
    "within",
    "without",
    "yes",
    "no",
    "yet",
  ];

  return stopwords_b;
}

//#endregion

//#region 189 Stop words C

function stopwords_c() {
  let stopwords_c = [
    "abeam",
    "able",
    "aboard",
    "abreast",
    "abroad",
    "absent",
    "accordance",
    "according",
    "account",
    "across",
    "addition",
    "adjacent",
    "ahead",
    "aint",
    "along",
    "alongside",
    "amid",
    "amnt",
    "among",
    "anything",
    "apart",
    "apropos",
    "apud",
    "arent",
    "around",
    "aside",
    "assuming",
    "astern",
    "astride",
    "atop",
    "away",
    "back",
    "bar",
    "behalf",
    "behest",
    "behind",
    "beneath",
    "beside",
    "besides",
    "beyond",
    "bout",
    "cannot",
    "cant",
    "case",
    "circa",
    "close",
    "come",
    "condition",
    "consequence",
    "couldnt",
    "couldve",
    "dare",
    "despite",
    "didnt",
    "doesnt",
    "dont",
    "due",
    "even",
    "event",
    "ever",
    "everything",
    "except",
    "far",
    "front",
    "get",
    "go",
    "goes",
    "going",
    "gonna",
    "got",
    "gotta",
    "hadnt",
    "havent",
    "hello",
    "hey",
    "hi",
    "im",
    "inside",
    "instead",
    "isnt",
    "ive",
    "know",
    "left",
    "less",
    "let",
    "lets",
    "lieu",
    "like",
    "many",
    "matter",
    "means",
    "mightnt",
    "mightve",
    "minus",
    "much",
    "mustnt",
    "mustve",
    "near",
    "nearer",
    "nearest",
    "need",
    "never",
    "next",
    "none",
    "nothing",
    "notwithstanding",
    "now",
    "off",
    "old",
    "one",
    "ones",
    "onto",
    "ontop",
    "opposed",
    "opposite",
    "order",
    "oughtnt",
    "outside",
    "owing",
    "past",
    "per",
    "place",
    "point",
    "post",
    "pre",
    "previous",
    "prior",
    "pro",
    "provided",
    "providing",
    "pursuant",
    "qua",
    "rather",
    "regard",
    "regarding",
    "regardless",
    "regards",
    "respect",
    "result",
    "right",
    "round",
    "sake",
    "sans",
    "save",
    "set",
    "shall",
    "short",
    "shouldnt",
    "shouldve",
    "since",
    "something",
    "soon",
    "spite",
    "subsequent",
    "suppose",
    "supposing",
    "tell",
    "thanks",
    "thatll",
    "thats",
    "therefore",
    "thous",
    "throughout",
    "thru",
    "thruout",
    "thus",
    "till",
    "times",
    "top",
    "toward",
    "towards",
    "underneath",
    "unless",
    "unlike",
    "unto",
    "upon",
    "upside",
    "us",
    "versus",
    "via",
    "view",
    "want",
    "wasnt",
    "well",
    "whats",
    "worth",
    "worthwhile",
    "wouldnt",
    "yonder",
  ];

  return stopwords_c;
}

//#endregion

//#region Modules

module.exports = {
  stopwords_a,
  stopwords_b,
  stopwords_c,
};

//#endregion
